// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
)

const (
	AudioCodecLossless AudioCodec = "Lossless"
	AudioCodecLossy    AudioCodec = "Lossy"
	AudioCodecOther    AudioCodec = "Other"
)

var ErrInvalidAudioCodec = fmt.Errorf("not a valid AudioCodec, try [%s]", strings.Join(_AudioCodecNames, ", "))

var _AudioCodecNames = []string{
	string(AudioCodecLossless),
	string(AudioCodecLossy),
	string(AudioCodecOther),
}

// AudioCodecNames returns a list of possible string values of AudioCodec.
func AudioCodecNames() []string {
	tmp := make([]string, len(_AudioCodecNames))
	copy(tmp, _AudioCodecNames)
	return tmp
}

// AudioCodecValues returns a list of the values for AudioCodec
func AudioCodecValues() []AudioCodec {
	return []AudioCodec{
		AudioCodecLossless,
		AudioCodecLossy,
		AudioCodecOther,
	}
}

// String implements the Stringer interface.
func (x AudioCodec) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AudioCodec) IsValid() bool {
	_, err := ParseAudioCodec(string(x))
	return err == nil
}

var _AudioCodecValue = map[string]AudioCodec{
	"Lossless": AudioCodecLossless,
	"lossless": AudioCodecLossless,
	"Lossy":    AudioCodecLossy,
	"lossy":    AudioCodecLossy,
	"Other":    AudioCodecOther,
	"other":    AudioCodecOther,
}

// ParseAudioCodec attempts to convert a string to a AudioCodec.
func ParseAudioCodec(name string) (AudioCodec, error) {
	if x, ok := _AudioCodecValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _AudioCodecValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return AudioCodec(""), fmt.Errorf("%s is %w", name, ErrInvalidAudioCodec)
}

// MarshalText implements the text marshaller method.
func (x AudioCodec) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AudioCodec) UnmarshalText(text []byte) error {
	tmp, err := ParseAudioCodec(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errAudioCodecNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *AudioCodec) Scan(value interface{}) (err error) {
	if value == nil {
		*x = AudioCodec("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseAudioCodec(v)
	case []byte:
		*x, err = ParseAudioCodec(string(v))
	case AudioCodec:
		*x = v
	case *AudioCodec:
		if v == nil {
			return errAudioCodecNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errAudioCodecNilPtr
		}
		*x, err = ParseAudioCodec(*v)
	default:
		return errors.New("invalid type for AudioCodec")
	}

	return
}

// Value implements the driver Valuer interface.
func (x AudioCodec) Value() (driver.Value, error) {
	return x.String(), nil
}

type NullAudioCodec struct {
	AudioCodec AudioCodec
	Valid      bool
	Set        bool
}

func NewNullAudioCodec(val interface{}) (x NullAudioCodec) {
	err := x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	_ = err            // make any errcheck linters happy
	return
}

// Scan implements the Scanner interface.
func (x *NullAudioCodec) Scan(value interface{}) (err error) {
	if value == nil {
		x.AudioCodec, x.Valid = AudioCodec(""), false
		return
	}

	err = x.AudioCodec.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullAudioCodec) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.AudioCodec.String(), nil
}

// MarshalJSON correctly serializes a NullAudioCodec to JSON.
func (n NullAudioCodec) MarshalJSON() ([]byte, error) {
	const nullStr = "null"
	if n.Valid {
		return json.Marshal(n.AudioCodec)
	}
	return []byte(nullStr), nil
}

// UnmarshalJSON correctly deserializes a NullAudioCodec from JSON.
func (n *NullAudioCodec) UnmarshalJSON(b []byte) error {
	n.Set = true
	var x interface{}
	err := json.Unmarshal(b, &x)
	if err != nil {
		return err
	}
	err = n.Scan(x)
	return err
}

// MarshalGQL correctly serializes a NullAudioCodec to GraphQL.
func (n NullAudioCodec) MarshalGQL(w io.Writer) {
	bytes, err := json.Marshal(n)
	if err == nil {
		_, _ = w.Write(bytes)
	}
}

// UnmarshalGQL correctly deserializes a NullAudioCodec from GraphQL.
func (n *NullAudioCodec) UnmarshalGQL(v any) error {
	if v == nil {
		return nil
	}
	str, ok := v.(string)
	if !ok {
		return errors.New("value is not a string")
	}
	if str == "null" {
		return nil
	}
	return n.UnmarshalJSON([]byte("\"" + str + "\""))
}
